# Generated by Django 3.2.5 on 2021-09-12 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_adopt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adopt',
            new_name='Beefriend',
        ),
    ]
