# Generated by Django 3.2.5 on 2021-09-14 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210914_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='suburb',
        ),
    ]
