# Generated by Django 3.2.5 on 2021-09-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_suburb'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='beehives',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
