# Generated by Django 3.2.5 on 2021-09-16 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20210916_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='min_goal',
        ),
    ]
