# Generated by Django 3.2.5 on 2021-09-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_project_beehives'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='beehives',
            field=models.IntegerField(null=True),
        ),
    ]
