# Generated by Django 3.2.5 on 2021-09-16 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_beehives'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='goal',
            new_name='min_goal',
        ),
    ]
