# Generated by Django 3.2.5 on 2021-09-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_project_min_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='min_required',
            field=models.IntegerField(null=True),
        ),
    ]
