# Generated by Django 3.2.5 on 2021-09-16 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0017_project_min_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='min_required',
        ),
        migrations.AlterField(
            model_name='beefriend',
            name='supporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporter_adoptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
