# Generated by Django 3.2.5 on 2021-09-16 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0018_auto_20210916_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beefriend',
            name='supporter',
        ),
        migrations.AddField(
            model_name='beefriend',
            name='beefriender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='befriender', to='users.customuser'),
            preserve_default=False,
        ),
    ]
