# Generated by Django 3.2.5 on 2021-09-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20210916_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='min_required',
            field=models.IntegerField(default=300),
        ),
    ]
