# Generated by Django 3.2.5 on 2021-09-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_project_min_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.JSONField(default=list),
        ),
    ]
