# Generated by Django 3.2.5 on 2021-09-21 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_alter_project_suburbs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beefriend',
            old_name='beefriender',
            new_name='beefriend',
        ),
        migrations.AlterField(
            model_name='beefriend',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beefriend', to='projects.project'),
        ),
    ]
